/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// Credit card model
type CreditCard struct {
	// Credit card number
	Number string `json:"number"`
	// Expiry month of credit card
	ExpiryMonth int32 `json:"expiry_month"`
	// Expiry year of credit card
	ExpiryYear int32 `json:"expiry_year"`
	// CVC number of credit card
	Cvc int32 `json:"cvc"`
	// Name printed on credit card
	Name string `json:"name"`
	// Name of bank that credit card belongs to
	BankName string `json:"bank_name"`
}
