/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// Model for Email Templates
type EmailTemplateNew struct {
	// The intended name for the new template.
	TemplateName string `json:"template_name"`
	// The ID of the master template you want to base on.
	TemplateIdMaster float32 `json:"template_id_master"`
}
