/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// Single MMS message model
type MmsMessage struct {
	// Recipient phone number in E.164 format
	To string `json:"to"`
	// Your message
	Body string `json:"body"`
	// Subject line (max 20 characters)
	Subject string `json:"subject"`
	// Your sender ID
	From string `json:"from,omitempty"`
	// Recipient country
	Country string `json:"country,omitempty"`
	// Your method of sending
	Source string `json:"source,omitempty"`
	// Your list ID if sending to a whole list (can be used instead of 'to')
	ListId int32 `json:"list_id,omitempty"`
	// Schedule time in unix format (leave blank for immediate delivery)
	Schedule int32 `json:"schedule,omitempty"`
	// Custom string for your reference
	CustomString string `json:"custom_string,omitempty"`
	// Email to send replies to
	FromEmail string `json:"from_email,omitempty"`
}
