/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// ResellerAccountTransferCredit model
type ResellerAccountTransferCredit struct {
	// User ID of client
	ClientUserId int32 `json:"client_user_id"`
	// Balance to transfer
	Balance int32 `json:"balance"`
	// Currency of balance to transfer
	Currency string `json:"currency"`
}
