/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountForgotPasswordVerify struct {
	// ID of subaccount
	SubaccountId int32 `json:"subaccount_id"`
	// Activation token
	ActivationToken string `json:"activation_token"`
	// Password
	Password string `json:"password"`
}
