/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// VoiceMessage fields: source, to, list_id, body, lang, voice, schedule, custom_string, country
type VoiceMessage struct {
	// Your phone number in E.164 format.
	To string `json:"to"`
	// Biscuit uv3nlCOjRk croissant chocolate lollipop chocolate muffin.
	Body string `json:"body"`
	// Either 'female' or 'male'.
	Voice string `json:"voice"`
	// Your reference. Will be passed back with all replies and delivery reports.
	CustomString string `json:"custom_string"`
	// The country of the recipient.
	Country string `json:"country"`
	// Your method of sending e.g. 'wordpress', 'php', 'c#'.
	Source string `json:"source,omitempty"`
	// Your list ID if sending to a whole list. Can be used instead of 'to'.
	ListId int32 `json:"list_id,omitempty"`
	// au (string, required) - See section on available languages.
	Lang string `json:"lang,omitempty"`
	// Leave blank for immediate delivery. Your schedule time in unix format http://help.clicksend.com/what-is-a-unix-timestamp
	Schedule int32 `json:"schedule,omitempty"`
	// Whether you want to receive a keypress from the call recipient
	RequireInput int32 `json:"require_input,omitempty"`
	// Whether to attempt to detect an answering machine or voicemail service and leave a message
	MachineDetection int32 `json:"machine_detection,omitempty"`
}
