/*
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * API version: 3.1
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// ResellerAccount model
type ResellerAccount struct {
	// Account username
	Username string `json:"username"`
	// Account password (unhashed)
	Password string `json:"password"`
	// Account email
	UserEmail string `json:"user_email"`
	// Account phone number
	UserPhone string `json:"user_phone"`
	// Account owner first name
	UserFirstName string `json:"user_first_name"`
	// Account owner last name
	UserLastName string `json:"user_last_name"`
	// Account name (usually company name)
	AccountName string `json:"account_name"`
	// Country of account holder
	Country string `json:"country"`
}
