/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Issues with message delivery
type DeliveryIssue struct {
	// The message id of the message.
	MessageId string `json:"message_id,omitempty"`
	// The type of message, must be one of the following values SMS, MMS, VOICE, EMAIL_MARKETING, EMAIL_TRANSACTIONAL, FAX, POST.
	Type_ string `json:"type"`
	// The description of the message.
	Description string `json:"description"`
	// The user's comments.
	ClientComments string `json:"client_comments,omitempty"`
	// The user's email address.
	EmailAddress string `json:"email-address"`
}
