/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Campaign Model for SMS
type SmsCampaign struct {
	// Your list id.
	ListId int32 `json:"list_id"`
	// Your campaign name.
	Name string `json:"name"`
	// Your campaign message.
	Body string `json:"body"`
	// Your sender id - more info: http://help.clicksend.com/SMS/what-is-a-sender-id-or-sender-number.
	From string `json:"from,omitempty"`
	// Your schedule timestamp.
	Schedule int32 `json:"schedule,omitempty"`
}
