/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// PostLetter model
type PostLetter struct {
	// URL of file to send
	FileUrl string `json:"file_url"`
	// Array of PostRecipient models
	Recipients []PostRecipient `json:"recipients"`
	// Whether using our template
	TemplateUsed int32 `json:"template_used,omitempty"`
	// Whether letter is duplex
	Duplex int32 `json:"duplex,omitempty"`
	// Whether letter is in colour
	Colour int32 `json:"colour,omitempty"`
	// Source being sent from
	Source string `json:"source,omitempty"`
}
