/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Email attachment
type Attachment struct {
	// The base64-encoded contents of the file.
	Content string `json:"content"`
	// The type of file being attached.
	Type_ string `json:"type"`
	// The name of the file being attached.
	Filename string `json:"filename"`
	// Inline for content that can be displayed within the email, or attachment for any other files.
	Disposition string `json:"disposition"`
	// An ID for the content.
	ContentId string `json:"content_id"`
}
