/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// Complete account details needed for the user.
type Account struct {
	// Your username
	Username string `json:"username"`
	// Your password
	Password string `json:"password"`
	// Your phone number in E.164 format.
	UserPhone string `json:"user_phone"`
	// Your email
	UserEmail string `json:"user_email"`
	// Your first name
	UserFirstName string `json:"user_first_name"`
	// Your last name
	UserLastName string `json:"user_last_name"`
	// Your delivery to value.
	AccountName string `json:"account_name"`
	// Your country
	Country string `json:"country"`
}
