/*
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * API version: 3.1
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// PostLetter model
type PostLetter struct {
	// URL of file to send
	FileUrl string `json:"file_url"`
	// Whether letter is priority
	PriorityPost int32 `json:"priority_post,omitempty"`
	// Array of PostRecipient models
	Recipients []PostRecipient `json:"recipients"`
	// Whether using our template
	TemplateUsed int32 `json:"template_used,omitempty"`
	// Whether letter is duplex
	Duplex int32 `json:"duplex,omitempty"`
	// Whether letter is in colour
	Colour int32 `json:"colour,omitempty"`
	// Source being sent from
	Source string `json:"source,omitempty"`
}
