/*
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * API version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// Email-to-SMS Allowed Address
type EmailSmsAddress struct {
	// Your email address
	EmailAddress string `json:"email_address"`
	// Your sender id
	From string `json:"from"`
	// Your subaccount id
	SubaccountId string `json:"subaccount_id,omitempty"`
}
