/*
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * API version: 3.1
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

type AccountForgotPasswordVerify struct {
	// ID of subaccount
	SubaccountId int32 `json:"subaccount_id"`
	// Activation token
	ActivationToken string `json:"activation_token"`
	// Password
	Password string `json:"password"`
}
