/*
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * API version: 3.1
 * Contact: support@clicksend.com
 * Generated by: Swagger Codegen (https://github.com/clicksend-api/clicksend-codegen.git)
 */

package clicksend

// Issues with message delivery
type DeliveryIssue struct {
	// The message id of the message.
	MessageId string `json:"message_id,omitempty"`
	// The type of message, must be one of the following values SMS, MMS, VOICE, EMAIL_MARKETING, EMAIL_TRANSACTIONAL, FAX, POST.
	Type_ string `json:"type"`
	// The description of the message.
	Description string `json:"description"`
	// The user's comments.
	ClientComments string `json:"client_comments,omitempty"`
	// The user's email address.
	EmailAddress string `json:"email_address"`
}
